stephy/CalendarPicker

CalendarPicker.js
Hi.
I changed the indentation to match the [node-style](https://github.com/felixge/node-style-guide#2-spaces-for-indention) guideline.
The reason I want a change is because it's really hard to read the code in the browser, and I think it is a good move to increase the overall quality of the project. :)
Kind regards,
Edvin
=> Converted indentation from tabs to 2 spaces

CalendarPicker/CalendarPicker.js
Hi
I added some validation to the props (on all components). 
I also added a `key` attribute to the `<Day />` and `<WeekDaysLabels />` components.
=> Added prop type validation and key attr

CalendarPicker/CalendarPicker.js, CalendarPicker/Styles.js, README.md
+ style selected Day (text + background)
=> Custom 'previous', 'next' titles, weekdays, months names. Start from monday or sunday. Style text

CalendarPicker/CalendarPicker.js
Arrow function callbacks after the state is set!
Call the onMonthChange function from getNext and getPrev to update the month as well as the year!
=> Fix issue #29, CalendarPicker now returns the currently selected date instead of the previously selected date.

CalendarPicker/CalendarPicker.js, CalendarPicker/makeStyles.js, index.ios.js
Any constructive feedback is welcome.
=> Adding date range support

package.json
=> Add babel-preset-expo to peerDependencies

CalendarPicker/index.js, README.md
Dynamically use height or width to accomodate different aspect ratios. 
See #71
=> Add height & width props to allow for dynamic sizing.

CalendarPicker/Day.js, CalendarPicker/DaysGridView.js, CalendarPicker/HeaderControls.js, CalendarPicker/Utils.js, CalendarPicker/index.js, README.md, package.json
=> Convert to Moment JS for dates.

CalendarPicker/__tests__/CalendarPicker-test.js, CalendarPicker/__tests__/__snapshots__/CalendarPicker-test.js.snap
Update the snapshots to reflect the recent changes in styling. Also, hard-coded the dates.
=> Fix Travis Test

CalendarPicker/index.js
=> Add default prop for onDateChange() callback

package.json
=> Move expo to devDependencies

CalendarPicker/DaysGridView.js, package.json
Update uuid dependency and remove outdated metadata in package.json
=> Update uuid and package.json

CalendarPicker/__tests__/CalendarPicker-test.js, CalendarPicker/__tests__/__snapshots__/CalendarPicker-test.js.snap, CalendarPicker/index.js
fix for issue # 122
it fix selectedStartDate and SelectedEndDate props passed in as props on init also
if props are changed then they properly updated
=> fix-issue122/selectedStartDateAndSelectedEndDate-does-not-work

CalendarPicker/index.js, README.md
Add a new props onSwipe trans to Swipe component ,for custom a callback when swipe event trigger
=> Add props onSwipe 

CalendarPicker/__tests__/__snapshots__/CalendarPicker-test.js.snap, CalendarPicker/index.js
The property style was mispelled. This fixes #142
=> Fix prop typo: syles -> style

CalendarPicker/Day.js, CalendarPicker/DaysGridView.js, CalendarPicker/index.js
Fixes #145
Usage:
```
<CalendarPicker
enableDateChange={false}
```
To disable selecting/changing dates.
=> Fixed enableDateChange

CalendarPicker/Controls.js, CalendarPicker/HeaderControls.js, CalendarPicker/index.js, README.md
Disable Previous / Next month buttons based on minDate and maxDate
=> Disable Previous / Next month buttons based on minDate and maxDate

CalendarPicker/Controls.js
Increases clickable areas to make it easier for user to hit the buttons.
=> Increase clickable area on next and previous buttons.

CalendarPicker/Day.js, CalendarPicker/DaysGridView.js, CalendarPicker/index.js, README.md
Currently there is no way to add styling to disabled dates.  Default color does not work well when using with a dark theme.
=> Add prop to add text styles to disabled dates.

CalendarPicker/HeaderControls.js, CalendarPicker/index.js, README.md
Modify to apply the attribute to change the order of year and month
=> Add prop: change order of the year and month style

README.md
Bringing type documentation for `handleOnPressDay` up to date with the code.
=> Fix arg type docs of handleOnPressDay

CalendarPicker/index.js
`resetSelections` method was not updating the UI
=> Fix resetSelections not working

CalendarPicker/index.js, README.md
Addresses issue https://github.com/stephy/CalendarPicker/issues/340
=> Add optional initialView prop to customize view

package.json
- Added a constraint to the `date-fns` version as a peerDependency
- Aligned `date-fns` version in `devDependencies` and `peerDependencies`
Addresses #367
=> Updated date-fns dependency version

CalendarPicker/DaysGridView.js, package.json
Update recyclerlistview to the latest version to address high vulnerabilities
=> Update recyclerlistview to the latest version

CalendarPicker/Day.js
update `Day.js` to resolve bug where `selectedDayTextStyle` overwrites `todayTextStyle`
=> Update Day.js to remove bug in todayTextStyle
