stephy/CalendarPicker

CalendarPicker/CalendarPicker.js
The setState method is done asynchronously in React Native. See this [link](https://facebook.github.io/react/docs/component-api.html#setstate).
>setState() does not immediately mutate this.state but creates a pending state transition. Accessing this.state after calling this method can potentially return the existing value.
=> Don't rely on state to be updated synchronously.

CalendarPicker/CalendarPicker.js, CalendarPicker/makeStyles.js
Disables the day if it's less than `minDate` or greater than `maxDate`.
Also disables next and previous links when appropriate.
Fixes #37.
For example, the following initialization:
```js
<CalendarPicker minDate={new Date(2016,6,4)} maxDate={new Date(2016,6,25)} />
```
Will produce the following:
And with only `maxDate`:
```js
<CalendarPicker maxDate={new Date(2016,6,25)} />
```
And with only `minDate`:
```js
<CalendarPicker minDate={new Date(2016,6,4)} />
```
=> Add min date and max date

CalendarPicker/CalendarPicker.js
This is necessary when you're changing the `selectedDate` prop of CalenderPicker programmatically.
For example, in our app after a user selects a date and clicks submit, we reset the form and set the CalendarPicker selectedDate to `new Date()`. However, the CalendarPicker calendar doesn't actually update.
This commit adds `componentWillReceiveProps`, which watches for new props passed to CalendarPicker and updates based on the new Props.
Works great! :)
=> Update Calendar on Props Change.

CalendarPicker/CalendarPicker.js
It works fine without it and thus is optional. Removes React Native warning when not used.
=> Remove `isRequired` for `screenWidth` prop.

CalendarPicker/index.js, README.md
The render() method refers to `initialDate` in props instead of state, allowing the parent to change initialDate and automatically update via render().  `currentMonth` and `currentYear` reference the initialDate prop, initially in componentDidMount and also as it's updated in componentWillReceiveProps.
If the parent does not pass in `initialDate`, it defaults to today.
=> Prop initialDate controls which date/month calendar opens to.

CalendarPicker/Controls.js, CalendarPicker/Day.js, CalendarPicker/DaysGridView.js, CalendarPicker/EmptyDay.js, CalendarPicker/HeaderControls.js, CalendarPicker/Weekdays.js, CalendarPicker/index.js, README.md, package.json
onMonthChange fires when Previous/Next is pressed.
[Line 60](https://github.com/stephy/CalendarPicker/pull/84/commits/2db5ec8af910ed73414f1c41e8003f20781d331d#diff-0b829010e731eca6770ccc0d87c6a789R60) fixes the `intitialDate`prop change state update.
See #83
=> Fix state update when initialDate prop changes. Add onMonthChange prop.

CalendarPicker/DaysGridView.js
This should fix the issue where the first day of the month is not correctly displayed when showing the calendar with monday as its start day.
=> Fixed startFromMonday functionality

CalendarPicker/DaysGridView.js, CalendarPicker/index.js, CalendarPicker/makeStyles.js, README.md
This PR adds a prop that enables a "square" shape on selected days, instead of the default circle. Also fixed a typo on `DEFAULT_TODAY_BACKGROUND_COLOR` in makeStyles.
=> add dayShape props

CalendarPicker/__tests__/CalendarPicker-test.js, CalendarPicker/__tests__/__snapshots__/CalendarPicker-test.js.snap
The last time the tests were fixed was in February 2019 in pull request #144, which is why the initialDate of new Date(2019, 1, 20) was chosen.
If the initialDate is not chosen, the date defaults to today, which is not stable over time for these tests.
=> Fixed the tests with the minimum number of changes.

.travis.yml
Updated the Linux distribution for the Travis tests to be Xenial, to pick up more recent versions of Node.js by default.
Both Node.js 6 and 7 are no longer supported/maintained by the Node.js project, so also specified the currently active Node.js LTS version (10) and the latest stable Node.js version (12).
See https://github.com/nodejs/Release and https://nodejs.org/en/about/releases/
See https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions for some minimal information on how this is specified in the .travis.yml file.
=> Travis: Updated the Linux distribution to Xenial and updated the Node.js versions

CalendarPicker/DaysGridView.js, CalendarPicker/__tests__/__snapshots__/CalendarPicker-test.js.snap
- If startFromMonday is false, startIndex needs to be assigned firstWeekDay modulo 7 (because otherwise if the first week day is Sunday, firstWeekDay is 7 from isoWeekday() and the index variable from guideArray is never >= 7, and so the first row just consists of 7 EmptyDay elements).
- Also split guideArray into dayArray and weekArray, since it is used for both days and weeks, but there can't be 7 rows of weeks in a calendar view for any month.
- Renamed the generateColumns() function to generateDatesForWeek() to better explain what it is doing.
- Removed the unnecessary intermediate "column" constant (it wasn't really being used).
- Renamed the 2 current value "index" variables in the map functions to better describe what they are being used for.
- Added some blank lines and spaces for …
=> Fixes issue #153 (first row is blank)

CalendarPicker/EmptyDay.js, CalendarPicker/HeaderControls.js, CalendarPicker/__tests__/__snapshots__/CalendarPicker-test.js.snap, CalendarPicker/index.js, README.md
We are using CalendarPicker for a cross-platform (iOS, Android, and Web) application within the federal government.  There are strict accessibility requirements which are tested.  For this component, we simply needed to add an accessibilityRole of `heading` for the month/year title of the calendar, and for web include an optional `headingLevel` prop.  The optional prop has no bearing unless the component is being used with react-native-web.
I also discovered that the `EmptyDay` component was using a touchable making the empty spaces "accessible", these were changed to not be accessible.
Thanks for this great and easy to use component!
=> Adds accessibilityRole to calendar title for 508 compliance

CalendarPicker/HeaderControls.js, CalendarPicker/Weekdays.js, CalendarPicker/index.js, README.md, package-lock.json
Hi,
I am using your library for calendar picker, and range picker. It works 100% fine.
But there are few my requirements, those I am unable to handle using old code.
My requirements:
- Remove top / bottom divider from Weekdays.
- Show different color for Sunday.
- And different colors for "Next" and "Previous" buttons.
So I forked your lib, and did some changes to fulfill my requirements. See screenshot below:
Here is code while using CalendarPicker:
`<CalendarPicker
textStyle={styles.calendarTextStyle}
weekdays={CALENDAR_WEEK_DAYS}
allowRangeSelection
previousTitle="<"
previousTitleStyle={{color: WHITE}}
nextTitle=">"
nextTitleStyle={{color: APP_MAIN_COLOR}}
dayLabelsCustomWrapper={{
borderBottomWidth: 0,
borderTopWidth: 0,
}}
selectedRangeStyle={styles.calendarRangeColor} …
=> Added support to customized the Weekdays wrapper style, sunday color, previous button and next button color.

README.md
Just two missing `}` in the README docs :)
=> Fix missing braces in README.md

CalendarPicker/Day.js
I think the parenthesis was wrong here, in consequence the "day" argument was passed to the `moment()` function instead of the `isAfter()` method. This would lead to the `day` argument to be effectively being ignored when using `maxRangeDuration` as an array, i.e. this use case might not always use as intended.
=> Fix call to moment.isSame(), remove unused import

README.md, package.json
Specify moment.js peerDep versions more accurately. This package uses moment.js APIs like `isAfter()` or `isSame()` which were introduced in version 2.0.0, so using this package with a lower moment.js version would not work.
=> Specify moment.js dependency version more accurately

README.md
Fix the documentation of prop types in the README.md where the props are used differently than documented
=> Fix type documentation for props

CalendarPicker/DaysGridView.js
Why
--
I've been using this package in Expo and the web build failed because ViewPropTypes is removed in RNW >= 0.12.1
In this PR
--
Replace ViewPropTypes with PropTypes as it has been deprecated in RNW >=0.12.1 https://github.com/necolas/react-native-web/issues/1537#issuecomment-584806182
(Inspired by: https://github.com/ozcanzaferayan/react-native-web-swiper/commit/0ef4ca89d62e59c0ce2cece6dc0edd133d3fd703)
=> fix: replace ViewPropTypes with PropTypes 

CalendarPicker/YearsHeader.js
Resolves #230 
- Check if maxDate & minDate is defined before checking while using restrictMonthNavigation
=> fix: use restrictMonthNavigation without defining maxDate & minDate

CalendarPicker/Day.js, CalendarPicker/index.js, CalendarPicker/makeStyles.js
This also changes the style of the first selected date if it's out of range for the second selection to match the valid dates instead of look disabled, however it will not be selectable. 
Fixes #238
=> Don't allow range of 0 when minRangeDates > 0

CalendarPicker/DaysGridView.js, CalendarPicker/Utils.js, CalendarPicker/Weekdays.js, CalendarPicker/__tests__/CalendarPicker-test.js, CalendarPicker/index.js, README.md
this PR fixes #266 
it allows setting first day of week from Sunday (0) to Saturday (6), I have tested with moment locale option changed, no issue so far
=> First day option

CalendarPicker/Scroller.js
While I think there are some bigger issues behind how the styles for the calendar are being set (derived state and whatnot), this fixes an issue where, on update of scroller style props, the scroller could render `null` as `height` was `undefined`. Root cause seems to be not passing the right argument to the `updateLayout` helper causing the helper to not create required styles. I observed this when using a parent's `onLayout` to dynamically set the width of the calendar causing the update after the callback was triggered.
Side note: I want to urge the use of TS in this project if ever possible as this bug could have been totally avoided with strong types.
=> Fix issue with editing scroller style on update

CalendarPicker/Day.js, CalendarPicker/DaysGridView.js, CalendarPicker/Month.js, CalendarPicker/Scroller.js, CalendarPicker/Utils.js, CalendarPicker/Year.js, CalendarPicker/YearsHeader.js, CalendarPicker/index.js, README.md, example/example/App.js, example/example/app.json, example/example/package.json, example/example_typescript/package.json, example/example_typescript/src/components/CalendarView/index.js, example/example_typescript/src/components/CalendarView/index.tsx, package.json
I think there are good reasons to replace [moment.js](https://github.com/moment/moment) with [date-fns](https://date-fns.org/).
A way lighter, more performant, more popular, library, without the mutability quirks of moment.
This PR removes all imports of, references to, and moment specific methods from the code base, and replaces it with equivalent utilities from `date-fns` - which is added as a dependency.
It should be fully backwards compatible with earlier versions.
I've updated the version to 8.0.0 and reflected the changes in the README file.
[Issue #360](https://github.com/stephy/CalendarPicker/issues/360)
=> Replace moment with date-fns

CalendarPicker/Day.js, CalendarPicker/DaysGridView.js, CalendarPicker/Month.js, CalendarPicker/Scroller.js, CalendarPicker/Utils.js, CalendarPicker/Year.js, CalendarPicker/YearsHeader.js, CalendarPicker/index.js, example/example/App.js, package.json
Switched to individual import of date-fns to allow for tree shaking.
Updated version to 8.0.0.
I've been using the alpha version in my own projects with no issues, and there seems to have been some traction of the alpha version with no complaints yet - so I think we're ready to release it.
=> Individual imports of date-fns + 8.0.0 release

CalendarPicker/Scroller.js, CalendarPicker/index.js
- It was using some weird non-existent date functions, probably left over from moment migration, fixed it to use the proper date-fns ones;
- Also it wasn't working properly the backwards range date selection due to a logic error on date comparison to the previously selected date (that was comparing to the wrong variable);
=> Fix months shifting to use proper date-fns methods and backwards range date selection

CalendarPicker/DaysGridView.js, package.json
When selecting a single date (not a date range), the Day component would not re-render when the start date was changed.
[Issue 376](https://github.com/stephy/CalendarPicker/issues/376)
This was due to an optimization avoiding this unecessary re-render when changing a selected date range.
https://github.com/stephy/CalendarPicker/assets/6737260/96794f17-7900-4eaf-9e57-ce824cd69ecd
=> Single date select re-render

CalendarPicker/DaysGridView.js
Fixes #378 
This issue was happening when firstWeekDay of month is 7 and firstDay prop value is 0 which make startIndex 7 but as per logic startIndex should be from 0 to 6, so this leads render of an empty row as first row.
Fix: Correct value of startIndex for this case should be 0. Hence added % 7 to restrict startIndex to be from 0 to  6.
=> fix: empty 1st row in Days Calendar

CalendarPicker/Day.js, package.json
Taking https://github.com/stephy/CalendarPicker/issues/383 and creating a simple PR.
Instead of having default props being defined as class components do, simply use javascript to default to an empty array when destructuring props
=> #383  support for defaultprops
